export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'

export const FETCH_RESOURCES = 'FETCH_RESOURCES'
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS'
export const FETCH_RESOURCES_FAILURE = 'FETCH_RESOURCES_FAILURE'
